//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDGModernizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDGModernizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FINAL {
            get {
                return ResourceManager.GetString("FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Aspect]
        ///&lt;AspectX,float,4,1.0f&gt;
        ///&lt;AspectY,float,4,1.0f&gt;
        ///&lt;WinZoom,float,4,640.0f&gt;
        ///$13a46, 68 00 00 00 3F 68 00 00 80 3F , 68 (AspectY) 68 (AspectX)
        ///$58a48, 68 00 00 00 3F 68 00 00 80 3F , 68 (AspectY) 68 (AspectX)
        ///$5a69b, 68 00 00 00 3F 68 00 00 80 3F , 68 (AspectY) 68 (AspectX)
        ///$5a81f, 68 00 00 00 3F 68 00 00 80 3F , 68 (AspectY) 68 (AspectX)
        ///$5c247, A3 F0 B7 59 00 , EB 14 90 90 90
        ///$19b7f0, 00 00 20 44 , (WinZoom)
        ///$19b800, 00 00 20 44 , (WinZoom)
        ///$19b810, 00 00 20 44 , (WinZoom)
        ///$19b820, 00 00 20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PRO_2 {
            get {
                return ResourceManager.GetString("PRO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SHINKANSEN {
            get {
                return ResourceManager.GetString("SHINKANSEN", resourceCulture);
            }
        }
    }
}
