//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDGModernizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDGModernizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DrawDistance]
        ///&lt;RendPow,float,4,0.6&gt;
        ///&lt;OkiDistArg,float,4,0.4&gt;
        ///$1DB0F4, CD CC CC 3E , (OkiDistArg)
        ///$1DB0F8, 66 66 66 3F , (RendPow)
        ///$C6ED4, 00 00 00 00 , (RendPow)
        ///;Fix magnification
        ///$7E504, D9 1D F8 B0 5D 00 , 6A 00 EB 0C 90 90
        ///$7E50F, E8 EC D3 FF FF , EB 03 90 90 90
        ///;Fix for outer view
        ///$23621, 74 6F , EB 6F
        ///
        ///[Aspect]
        ///&lt;AspectX,float,4,1.0&gt;
        ///&lt;AspectY,float,4,0.5&gt;
        ///$178EB, 68 00 00 00 3F 68 00 00 80 3F , 68 (AspectY) 68 (AspectX)
        ///$17A5F, 68 00 00 00 3F 68 00 00 80 3F , 68 (AspectY) 68 (AspectX)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FINAL {
            get {
                return ResourceManager.GetString("FINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon1 {
            get {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Aspect]
        ///&lt;AspectX,float,4,1.0&gt;
        ///&lt;AspectY,float,4,1.0&gt;
        ///&lt;WinZoom,float,4,640.0&gt;
        ///;ExecViewCom
        ///$13a46, 68 00 00 00 3F 68 00 00 80 3F , 68 (AspectY) 68 (AspectX)
        ///;WinInit
        ///$5a690, 68 00 00 20 44 , 68 (WinZoom)
        ///$5a69b, 68 00 00 00 3F 68 00 00 80 3F , 68 (AspectY) 68 (AspectX)
        ///;WinAlloc
        ///$5a814, 68 00 00 20 44 , 68 (WinZoom)
        ///$5a81f, 68 00 00 00 3F 68 00 00 80 3F , 68 (AspectY) 68 (AspectX)
        ///;Other
        ///$5c247, A3 F0 B7 59 00 , EB 14 90 90 90
        ///$19b7f0, 00 00 20 44 , (WinZoom)
        ///$19b800, 00 00 20 44 , (WinZoom)
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PRO_2 {
            get {
                return ResourceManager.GetString("PRO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Aspect]
        ///&lt;AspectX,float,4,1.0&gt;
        ///&lt;AspectY,float,4,1.0&gt;
        ///&lt;AspectRatio,float,4,1.0&gt;
        ///&lt;WinZoom,float,4,640.0&gt;
        ///;WinProjection
        ///$d385, 68 00 00 80 3F, 68 (AspectX)
        ///$d3b1, 68 CD CC 4C 3F, 68 (AspectX)
        ///$807b9, 68 00 00 80 3F, 68 (AspectX)
        ///$9b39f, 68 00 00 80 3F, 68 (AspectX)
        ///
        ///;WinAspect
        ///;$3e06, C7 44 24 00 00 00 80 3F, C7 44 24 00 (AspectX)
        ///;$807c4, 68 6e db b6 3f, 68 (AspectX)
        ///;$9b3aa, 68 6e db b6 3f, 68 (AspectX)
        ///
        ///;Aspect
        ///$ca350, 6e db b6 3f, (AspectRatio)
        ///
        ///[DrawDistance]
        ///&lt;RendPow,float,4,0.5625&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SHINKANSEN {
            get {
                return ResourceManager.GetString("SHINKANSEN", resourceCulture);
            }
        }
    }
}
